# Generated by Django 5.1.6 on 2025-02-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('Hiredate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('totalbeds', models.IntegerField()),
                ('availablebeds', models.IntegerField()),
            ],
        ),
    ]
